name: UltimateVotePlus
main: com.minkang.ultimate.voteplus.Main
version: 1.4.5
api-version: 1.16
author: MinGang
commands:
  자동공지:
    description: 자동 공지 관리
    usage: /자동공지 [켜기|끄기|다음|강제|리로드]
    permission: ultimatevoteplus.admin
  추천:
    description: 추천 링크 안내 및 관리
    usage: /추천
permissions:
  ultimatevoteplus.admin:
    description: VotePlus 관리 권한
    default: op
