name: Build (Java 11)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Verify toolchain
        run: |
          java -version
          mvn -version

      - name: Build
        run: mvn -U -B -DskipTests clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/*.jar
          if-no-files-found: error
